deployctl.ts
src/subcommands/check.ts
src/subcommands/run.ts
src/subcommands/types.ts
tests/help_test.ts

fix: --help output should go to stdout

---

src/runtime.bundle.js
src/runtime.js
tests/run_test.ts
tests/testdata/timers.js

Delete timer methods from globalThis

---

types/deploy.ns.d.ts

chore: update the deploy.ns types

---

examples/serve_local.ts
src/runtime.bundle.js
src/runtime.js
tests/run_test.ts
tests/testdata/data.json

Introduces support to serve local files during local development.
Closes #20
Closes https://github.com/denoland/deploy_feedback/issues/3

feat: support serving local files

---

src/utils/info.ts
tests/run_test.ts
tests/testdata/syntax_error_dot_js

fix: don't panic on syntax error

---

deps.ts

chore: bump semver dependency

---

deps.ts

Locally, ran `make test` and all tests passed. Test results attached with the PR. LMK if you guys need anything else before this can be merged.
Thanks ❤️
<hr />
<details>
<summary>Test results</summary>
```sh
deno test -A --unstable
running 8 tests from file:///Users/kimchi/dev/kitchen/deployctl/tests/help_test.ts
test deployctl ... ok (150ms)
test deployctl -V ... ok (141ms)
test deployctl --version ... ok (135ms)
test deployctl -h ... ok (141ms)
test deployctl run -h ... ok (146ms)
test deployctl types -h ... ok (155ms)
test deployctl check -h ... ok (180ms)
test deployctl upgrade -h ... ok (217ms)
running 11 tests from file:///Users/kimchi/dev/kitchen/deployctl/tests/run_test.ts
test deployctl run ./examples/hello.js ... ok (1620ms)
test deployctl run ./examples/echo.js ... ok (1602ms) …
```

Update dependencies to latest

---

.github/workflows/ci.yml
deps.ts
tests/deps.ts

This PR updates deno_std versions to pass the canary CI.

chore: update std version

---

.github/workflows/test.yml
action/index.js

In #101, `cwd` in `action.yml` was renamed to `root`
It looks like `action/index.js` needs to be changed as well

fix(action): use `root` instead of `cwd`

---

.github/workflows/ci.yml
.github/workflows/test.yml

https://github.com/actions/checkout#checkout-v3

chore: bump actions checkout

---

src/subcommands/deploy.ts

This PR adds log message `Uploading all files from the current dir ($CWD)` to make it clear that the command uploads everything from CWD
related: #111

feat(deploy): log uploading directory

---

deployctl.ts
src/subcommands/deploy.ts

feat(deploy): add --dry-run option

---

src/args.ts
src/config_file.ts
src/subcommands/deploy.ts
src/utils/walk.ts

feat: Support multiple `--include` and `--exclude` args, and persist them to deno.json

---

action/deps.js
deps.ts
src/subcommands/deploy.ts
src/utils/walk.ts

Also fixes `--include`'s ability to include subdirectories

feat: support glob patterns in `--include` and `--exclude`

---

deployctl.ts
src/subcommands/upgrade.ts

Fix: #223 
See: https://github.com/denoland/deployctl/blame/ad8328ef14088b26a27762c2bf41b47e5b8073c4/src/utils/api.ts#L19

Fix missing permission `--allow-sys`

---

.github/workflows/test.yml
action.yml
action/shim.js

bump node to 20

---

src/subcommands/projects.ts
src/utils/api.ts
src/utils/api_types.ts

Feat(projects show): Always show org-id, and show name of user when org is the personal account.

---

deps.ts
src/args.ts
src/subcommands/deployments.ts
src/subcommands/logs.ts
src/subcommands/projects.ts
src/utils/api.ts
src/utils/api_types.ts

Feat: `deployments list` subcommand

---

src/subcommands/deployments.ts
src/subcommands/projects.ts
src/utils/api.ts

Fix: deployments show with personal orgs

---

action/deps.js
action/index.js
src/subcommands/deploy.ts
src/utils/mod.ts
src/utils/walk.ts
src/utils/walk_test.ts

- add `await` to deal with a floating promise
- exclude `node_modules` from deployment assets by default
Resolves #319

fix(action): address test failures

---

.github/workflows/ci.yml

fix(ci): address segfault by running action/deps.js up-to-date check on windows

---

src/subcommands/deploy.ts

Fix: honor `--prod` flag when using `--env-file` or `--env` flags
