denoland/deployctl

- src/subcommands/check.ts
- src/subcommands/run.ts
- src/utils/entrypoint.ts
- tests/run_test.ts
`run` and `check` subcommands share the same algorithm for parsing the entrypoint. This PR creates the util for it and reduces the duplicated code. This PR also adds the test cases for invalid entrypoint inputs.
> refactor: create util for parsing entrypoint

- deployctl.ts
- deps.ts
- src/subcommands/upgrade.ts
- src/version.ts
- tests/help_test.ts
```
deployctl upgrade
Upgrade deployctl to the given version (defaults to latest).
To upgrade to latest version:
deployctl upgrade
To upgrade to specific version:
deployctl upgrade 1.2.3
The version is downloaded from https://deno.land/x/deploy/deployctl.ts
USAGE:
deployctl upgrade [OPTIONS] [<version>]
OPTIONS:
-h, --help        Prints help information
ARGS:
<version>         The version to upgrade to (defaults to latest)
```
Closes #2
> feat: add `upgrade` subcommand

- deployctl.ts
- deps.ts
- examples/env.ts
- src/subcommands/run.ts
- src/utils/run.ts
- tests/run_test.ts
- tests/testdata/example.env
This PR adds `--env` flag to the `run` subcommand to allow loading environment variables from a `.env` file.
Closes #19
> feat(run): add --env flag to load environment variables

- src/runtime.bundle.js
- src/runtime.js
- tests/run_test.ts
- tests/testdata/respond_twice.js
This PR introduces changes to throw on multiple respondWith calls and matches the behaviour of Deno Deploy.﻿
> fix: error on multiple respondWith calls

- examples/with_nonexistent_dep.js
- src/error.ts
- src/subcommands/check.ts
- src/subcommands/run.ts
- src/utils/info.ts
- tests/check_test.ts
- tests/run_test.ts
This commit fixes module resolution errors being swallowed in --watch,
and resulting in a non descript "Not Found" error. This commit correctly
handles and displays these errors.
Fixes #34
> fix: handle module resolution errors with --watch

- .github/workflows/ci.yml
- README.md
- deployctl.ts
- deps.ts
- src/runtime.js
- src/subcommands/upgrade.ts
- src/utils/fetch_latest.ts
- src/utils/info.ts
- src/utils/run.ts
**How does it work?**
When a user runs deployctl, we use a web worker to fetch and store the latest release information at `$HOME/.deno/deployctl/update.json`. The information is valid for 24 hours. We check if the information is valid on consecutive runs and if the user's version is the latest. If not the latest, we display the update message. And if the information is not valid, we rerun the web worker.
It looks like the below.
```
➜  deployctl check examples/echo.js          
A new release of deployctl is available: 0.2.0 -> 0.3.0
To upgrade, run `deployctl upgrade`
https://github.com/denoland/deployctl/releases/tag/0.3.0
OK
➜  deployctl run examples/echo.js  
A new release of deployctl is available: 0.2.0 -> 0.3.0
To upgrade, run `deployctl upgrade` …
```
> feat: notify user about new version

- src/runtime.js
Following https://github.com/lucacasonato/deno_local_file_fetch/pull/10, files larger than 32kb were sometimes scrambled because the buffer wasn't copied and was overwritten
Upgrading to latest release should fix this issue and make large local files load correctly
> fix: upgrade fetch polyfill to support large files

- src/subcommands/run.ts
- src/utils/run.ts
Just something I noticed while using `deployctl`.
Thanks ❤️
> Fix typo in CLI help instructions: ‘envirnoment’ → ‘environment’

- src/subcommands/deploy.ts
- src/utils/api.ts
Displays the x-deno-ray id when the error is an internal server error.
Not sure where to include this update for action.
> feat: include x-deno-ray in error message

- README.md
Link was broken. Instead, we could link to the access token page.
> docs: Update link for access token

- .github/workflows/ci.yml
`deno cache` no longer performs type checking by default. This replaces that with `deno check`  to detect type errors in CI
> chore(ci): use `deno check` instead of `deno cache`

- src/subcommands/logs.ts
- src/subcommands/upgrade.ts
- src/utils/api_types.ts
- src/version.ts
- tests/utils.ts
We will soon update the response type of the log streaming endpoint so that it's made more TypeScript friendly and easier to work with the backend. So this commit fixes the type accordingly, and bumps the version to 1.6.0.
> update log response types of log streaming endpoint

- .github/workflows/ci.yml
- src/subcommands/upgrade.ts
- src/version.ts
- tests/utils.ts
This commit migrates to `Deno.Command` from `Deno.run`. This migration requires the minimum supported Deno version to be 1.28.3.
Closes #153
> switch to `Deno.Command`

- src/subcommands/deploy.ts
This tweaks `deploy` behavior on empty projects, pushing the initial deployment to prod and telling the user about futher updates requiring `--prod` flag usage.
It also enhances the final status message in order to record which environment got updated (production or preview).
> feat(deploy): push initial deployment to prod

- src/subcommands/logs.ts
- src/subcommands/logs_test.ts
> fix(logs): support project name in positional argument

- .github/workflows/ci.yml
- deno.lock
- src/subcommands/deploy.ts
- src/subcommands/logs.ts
- src/utils/access_token.ts
- src/utils/api.ts
- src/utils/spinner.ts
- src/utils/token_storage.ts
- src/utils/token_storage/darwin.ts
- src/utils/token_storage/memory.ts
- Uses Keychain for storing the token in Darwin. Other OSes store the token in memory (thus have to provision a new token on every deployment)
- A separate issue will implement file storage: #182
> feat: Automatic token provisioning on deploy

- src/subcommands/deploy.ts
- src/utils/api.ts
https://github.com/denoland/deployctl/assets/4871949/7c5f93ea-88fb-4524-a1ee-29b557cbfe43
> feat: Create project if not found

- src/utils/api.ts
Fixes #188
This commit sets `accept: application/x-ndjson` header when fetching live logs.
The backend API returns newline-delimited JSON in case of `accept: application/x-ndjson` _OR_ no accept header with the priority of `application/json` being higher than `application/x-ndjson`. In other words, it returns pure JSON response only when the accept header is present such that `application/json` has higher precedence than `application/x-ndjson`. So in general it defaults to newline-delimited JSON, but we got this issue because all API calls made by deployctl set `accept: application/json` explicitly.
> fix: set `accept: application/x-ndjson` in fetching live logs

- src/subcommands/deploy.ts
> fix: always store project-id in deno.json

- src/args.ts
- src/config_inference.ts
- src/subcommands/deploy.ts
- src/utils/api.ts
- src/utils/api_types.ts
- src/utils/organization.ts
> feat: Support creating projects to orgs other than the personal org

- src/version.ts
`deployctl` has been using `Deno.Command` for a while, which was stabilized in Deno v1.31.0
> chore: Bump `MINIMUM_DENO_VERSION`

- src/config_inference.ts
- src/utils/access_token.ts
Currently the fallback works when the open command fails, but not when spawning the open command itself. This PR addresses it.
Towards #254
> fix: Fallback to manual navigation when opening the browser automatically during token provisioning fails

- src/utils/access_token.ts
> fix: Windows support for automatic token provisioning

- .github/workflows/ci.yml
- README.md
- deno.json
- deployctl.ts
- examples/fresh/components/Button.tsx
- examples/fresh/routes/_app.tsx
- examples/fresh/routes/api/joke.ts
- examples/fresh/routes/greet/[name].tsx
- examples/fresh/twind.config.ts
- src/subcommands/api.ts
- src/subcommands/deploy.ts
- src/subcommands/deployments.ts
- src/subcommands/projects.ts
- src/subcommands/top.ts
- src/utils/api.ts
- src/utils/crons.ts
- src/utils/env_vars.ts
- src/utils/organization.ts
- src/utils/spinner.ts
- src/utils/walk.ts
- src/version.ts
This commit bumps the minimum required Deno version to 1.41.1 since in fact this is the real minimum version required to actually use the current deployctl. The following error log will appear if we try to run deployctl using Deno 1.41.0:
```console
deno 1.41.0 (release, aarch64-unknown-linux-gnu)
v8 12.1.285.27
typescript 5.3.3
✅ Successfully installed deployctl
/root/.deno/bin/deployctl
A new release of Deno is available: 1.41.0 → 1.42.4 Run `deno upgrade` to install it.
error: Uncaught (in promise) TypeError: Importing a JSR package via an HTTPS URL is not implemented. Use a jsr: specifier instead for the time being.
const fs = await import("./token_storage/fs.ts");
^
at async https://jsr.io/@deno/deployctl/1.12.0/src/utils/token_storage.ts:33:14
```
Upgrading Deno to 1.41.1 solves …
> chore: bump minimum Deno version to 1.41.1

- deno.lock
- src/subcommands/logs_test.ts
Currently the CI on the main branch is red because non-zero exit code has started to be considered as test failure since Deno 1.44.0. 
```
ERRORS 
parseArgsForLogSubcommand ... specify invalid format in since => ./src/subcommands/logs_test.ts:51:11
error: Error: Test case finished with exit code set to 1.
await t.step("specify invalid format in since", () => {
^
at exitSanitizer (ext:cli/40_test.js:113:15)
at async Object.outerWrapped [as fn] (ext:cli/40_test.js:134:14)
at async TestContext.step (ext:cli/40_test.js:492:22)
at async file:///Users/runner/work/deployctl/deployctl/src/subcommands/logs_test.ts:51:3
parseArgsForLogSubcommand ... specify invalid format in until => ./src/subcommands/logs_test.ts:55:11
error: Error: Test case finished with exit code set to 1.
await t.step("specify …
```
> test: set exit code to 0 to get invalid args tests to pass

- action/README.md
"documentation" was misspelled.
> docs(action): fix typo in action/README.md
